# Use official Node.js image as the base image
FROM node:14 AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies (including dev dependencies)
# RUN npm install --only=production
RUN npm install

# Copy the entire project to the working directory
COPY . .

# Compile TypeScript to JavaScript and install production dependencies
# RUN npm run build --prod

# Expose the port the app runs on
EXPOSE 3000

# RUN npm run start
# Command to run the application
# CMD ["node", "dist/index.js"]
